#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# GameMT E5 Plus audio defaults. Board quirk (stock dts: out-l2spk-r2hp +
# spk-ctl-gpios): the speakers are fed from the HP output path through an
# external amp (GPIO4_C2, driven by the speaker-amp dts node) - Playback Mux
# must stay HP; RK817's SPKOUT pin is wired to nothing. Master 96% matches
# the stock Android DAC tuning (-3.75 dB, hp-volume 0x0a); the boot default
# of 100% clips on these small speakers.
# Runs after the RK3566 platform quirk and overrides its audio path: both
# the SPK and HP positions must point at the HP path.

cat <<EOF >/storage/.config/profile.d/002-audio_path
DEVICE_PLAYBACK_PATH_SPK="HP"
DEVICE_PLAYBACK_PATH_HP="HP"
DEVICE_PLAYBACK_PATH="Playback Mux"
EOF

amixer -c 1 -q sset "Playback Mux" HP
amixer -c 1 -q sset "Internal Speakers" on
amixer -c 1 -q sset Master 96% on
